GET http://localhost:5000/bootcamps

###

GET http://localhost:5000/bootcamps/6115dbdbc6d9591fd536f60d

###
POST http://localhost:5000/bootcamps
Content-Type: application/json

{
    "name": "FlatIron School",
    "yearEstablished": 2012,
    "programType": "All 3",
    "programLength": 30,
    "courseOfferings": ["Software Engineering", "Data Science", "Cyber Security"],
    "averageRating": 10
}

###

DELETE http://localhost:5000/bootcamps/6115dbdbc6d9591fd536f60d

###
PATCH http://localhost:5000/bootcamps/6115dbdbc6d9591fd536f60d
Content-Type: application/json

{
    "averageRating": 8
}